eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8200/eureka/

hystrix:
  command:
    default:
      metrix:
        rollingPercentile:
          numBuckets: 60
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
spring:
  rabbitmq:
    host: sc-rabbitmq
